
GRID_UNIT_PX=8
APP_ENTRY=Main.qml
OPTIONS=-I prototype-toolkit

QMLSCENE_BIN=QT_DEVICE_PIXEL_RATIO=1 QT_SCALE_FACTOR=1 GRID_UNIT_PX=$(GRID_UNIT_PX) qmlscene

all: run

run:
	$(QMLSCENE_BIN) $(OPTIONS) $(APP_ENTRY)

